### ISSUE TITLE
Success messages are only shown if silent: true

### ISSUE THREAD

**Issue by rbhalla** [thredup/rollbar-sourcemap-webpack-plugin#16]
I think this is quite a confusing flag if that's truly the case.

**Comment by brandondoran** [comment]
Thanks for the feedback. Yes, that would be confuing if it was the case. This should not be the case though. I tested by setting `silent: true` in the options and there is no output. When `silent` is not explicitly set or when `silent: true`, I do indeed see output.  The output will be like:
```bash
Uploaded app-400c9f3307aad5273218.js.map to Rollbar
```

Could you give some examples of what you're seeing?

Here's my output from running the react example (in examples/react):
```bash
# First edit the rollbar tokens in webpack.config.babel.js
# and the S3 credentials or just comment out the S3 related code
npm install
npm run build
```
![screen shot 2016-07-15 at 9 29 01 am](https://cloud.githubusercontent.com/assets/1189930/16881373/c5211144-4a6e-11e6-85fc-378fab7d72d1.png)

There is also a test case to test that `console.info` is not called when `silent=true`. I will also add a test to verify that it is called when `silent=false` (or not specified).

**Comment by rbhalla** [comment]
@brandondoran, apologies for the late reply.

It turned out this was completely down to caching issues with CircleCI. While it seemed reproducible when I first posted this, I haven't been able to replicate it since then.

Reading the source and https://github.com/thredup/rollbar-sourcemap-webpack-plugin/pull/18 has convinced me that this is not at all an issue. 

Thank you for the thorough response though.

**Comment by brandondoran** [comment]
@rbhalla Ah, I've run into my fair share of caching issues with CircleCI as well. Thanks for your response and for closing!
