### ISSUE TITLE
NextJs dynamic routing not resolving to source map

### ISSUE THREAD

**Issue by luujam2** [thredup/rollbar-sourcemap-webpack-plugin#162]
When using NextJS dynamic routing (`[a]/b.js`) the `[` and `]` characters become HTML encoded characters when referenced in the script dependencies on the page (i.e. `%5Ba%5D/b.js`)

When the Rollbar plugin uploads the minified source files and sourcemaps they're uploaded against the plain text (`[a]/b.js`). Therefore when an error occurs on the page, the sourcemap is unable to be resolved as the filenames don't match exactly.

Would it be possible to create a flag (e.g. `encodeFilenames`) and allow that to be passed in to the plugin?

Thanks

**Comment by brandondoran** [comment]
@luujam2 that seems easy enough and I suppose it makes sense to do here.

**Comment by luujam2** [comment]
Hey @brandondoran I've created a PR. Let me know what you think
