### ISSUE TITLE
Code splitted sourcemaps not uploaded, despite being emitted by webpack

### ISSUE THREAD

**Issue by oller** [thredup/rollbar-sourcemap-webpack-plugin#27]
Hi there, this plugin has saved me a lot of shell script headaches, thank you!

I'm having trouble getting the plugin to upload *all* sourcemaps.  In my instance, it detects and correctly uploads:

- main.[hash].js
- vendor.[hash].js

Both of which are specified in the `entry` object.

However webpack is also generating `n` chunks for me based on `require.ensure` code splitting for the modules within the app. For this particular app, n = 0 through to 4, so 5 additional chunks.

- n.[hash].js 

I can see these emitted by webpack and written to my `dist` dir.

My config:
```js
        new RollbarSourceMapPlugin({
            accessToken: "******",  // RollBar post_server_item
            version: childProcess.execSync("git rev-parse HEAD").toString(),  // Get hash of last commit
            publicPath: "http://example.com"
        })
```

The docs states if `includeChunks` as an option is omitted, all webpack emitted sourcemap files will be uploaded, however this doesn't seem to be the case.  Any tips?

Thanks! 🎄 🎅  🎄

**Comment by brandondoran** [comment]
Hi @oller,
Great to hear this has been useful for you!

It looks like this is indeed a bug. For our dymanic/route chunks we're giving them names rather than ids so this is probably why we haven't run into this. But yes, the intent is that it should work for your use case. I'll look into a fix for this.

Thanks for submitting the issue!

**Comment by oller** [comment]
Thanks @brandondoran, that's right - I'm not explicitly naming these chunks at all, just letting webpack deal with them as it builds the app, so it'll be following whatever `webpack`'s default naming convention / behaviour is for hitting split points.

Let me know if there's anything I can do to help.

Thanks

**Comment by oller** [comment]
Looks good to me 👍 

I'll test again once it's merged into master and released.  Thanks again for the great plugin!
