### ISSUE TITLE
Does this work with Webpack2?

### ISSUE THREAD

**Issue by NullVoxPopuli** [thredup/rollbar-sourcemap-webpack-plugin#34]
I have this in my production.js, but I see in rollbar that no sourcemaps have been uploaded

```js

config.plugins.push(
  new RollbarSourceMapPlugin({
    accessToken: process.env.ROLLBAR_POST_SERVER_ITEM,
    version: process.env.ROLLBAR_VERSION,
    publicPath: `${process.env.API_HOST}/assets`
  })
)

module.exports = config;
```

There doesn't seem to be any rollbar-related output in my build -- is this normal?

**Comment by brandondoran** [comment]
Yes, this is in use with Webpack 2 in production. When you run your build, you should be seeing output like:
```bash
Uploaded vendor-15-5f105f75.js.map to Rollbar
Uploaded app-16-f5086aff.js.map to Rollbar
```

I don't see anything wrong with that config snippet. Some things to try:
- Are sourcemaps actually being generated in your build? If not, you wouldn't see any output from this plugin.
- Take a look in rollbar and see if you see any sourcemaps: https://rollbar.com/ACCOUNT/PRJECT/settings/source_maps/

If you have a public repo, I can take a closer look.

**Comment by piotrd** [comment]
Same question about Webpack 3 and 4 - has anyone tested that?

**Comment by brandondoran** [comment]
Hello @piotrd. Here at ThredUP we are using it in production with Webpack 3. We have not no tried with Webpack 4 yet.  But we plan on it soon.

**Comment by brandondoran** [comment]
Closing as the original question about the plugin working in webpack 2 is answered.
