### ISSUE TITLE
CRA usage

### ISSUE THREAD

**Issue by alexo382** [thredup/rollbar-sourcemap-webpack-plugin#466]
Hi,

Could I please get some tips on how to use this with create-react-app? 

Thanks!

**Comment by brandondoran** [comment]
Hi @alexo382, to my knowledge CRA doesn't expose the webpack config so in order to customize it you would have to eject.

**Comment by brandondoran** [comment]
Update: It looks like there are some workarounds to ejecting: https://marmelab.com/blog/2021/07/22/cra-webpack-no-eject.html
