### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by seangoedecke** [thredup/rollbar-sourcemap-webpack-plugin#51]
Hi! I'd like to use this package with a self-hosted Rollbar instance, but it looks like there hasn't been a release of this package since that commit. I can pin to a git commit hash but I'd rather not - any plans for releasing a new version?

**Comment by brandondoran** [comment]
@seangoedecke yes, will get a new release out by the end of the weekend.

**Comment by brandondoran** [comment]
@seangoedecke 2.3.0 is released: https://github.com/thredup/rollbar-sourcemap-webpack-plugin/commit/b7d1981fabefae97cb5882e09c4f4c746a12a175

**Comment by seangoedecke** [comment]
Thanks!
