### ISSUE TITLE
Rollbar 502 gateway issue

### ISSUE THREAD

**Issue by cain** [thredup/rollbar-sourcemap-webpack-plugin#516]
Hello! All of a sudden our CI build has shown this error for our build:

`ERROR in RollbarSourceMapPlugin: failed to upload 5b0b540.js.map to Rollbar: 502 - Bad Gateway`
  
  
  Anyone else having this issue? Nothing has changed on our side and api keys still look good

**Comment by mashrafdev** [comment]
same

**Comment by macgill4444** [comment]
We are seeing the same thing too.

**Comment by RayWelker** [comment]
I'm seeing errors part way through the upload.

Sometime the upload is successful, but mostly I'm seeing errors.

```
Uploaded 2.d7200ea5.chunk.js.map to Rollbar
Uploaded 16.d7200ea5.chunk.js.map to Rollbar
Uploaded 3.d7200ea5.chunk.js.map to Rollbar
Uploaded 4.d7200ea5.chunk.js.map to Rollbar
Failed to compile.

RollbarSourceMapPlugin: failed to upload 12.d7200ea5.chunk.js.map to Rollbar

```

**Comment by macgill4444** [comment]
@RayWelker we're seeing the same thing. I reached out to Rollbar support and they said they're investigating this issue now.  I'll post their response here when I get it. 

We've seen this error maybe one in every 10 sourcemap uploads the past 6 months but it's showing up in every single upload as of a couple days ago.

**Comment by cain** [comment]
@macgill4444 thanks! Keep us updated :) 

<img width="804" alt="CleanShot 2023-02-14 at 11 49 08@2x" src="https://user-images.githubusercontent.com/15246256/218609399-a662f380-dc4a-4952-b2f6-f35a8ec87c3d.png">

**Comment by macgill4444** [comment]
@cain - I just got a response and it looks like the issue is fixed. I'm going to try right now I'll let you know how it goes. Pasted the response below.

`
Hi Macgill, Our Engineering team have been investigating 2 issues related to source map upload. For people who started experiencing 502/504 errors on or after Saturday we believe the issue is fixed. I believe that you fall into this category. Please let me know if you are still experiencing the problem.
`

**Comment by cain** [comment]
@macgill4444 thanks let me know if it's working for you!

**Comment by cain** [comment]
Just re-added it to our CI and build worked, thanks guys

**Comment by AlejandroDaneri** [comment]
Could this issue be coming back? I've been running into it again over the last few weeks.

```

RollbarSourceMapPlugin: failed to upload ../pages/api/client/[id]/chat/config.js.map to Rollbar: 502 - Bad Gateway 
```
