### ISSUE TITLE
Uploading the bundle to rollbar, not the map file

### ISSUE THREAD

**Issue by ailadson** [thredup/rollbar-sourcemap-webpack-plugin#54]
**What happens:** After the bundle is built, when I check the Rollbar Source Maps Dashboard, all I see is `bundle.js`.
**What I expect:** To see the `bundle.js.map` file in the Rollbar Source Maps Dashboard. 

My `webpack.config.js` file
```
const path = require('path');
const RollbarSourceMapPlugin = require('rollbar-sourcemap-webpack-plugin');

const PUBLIC_PATH = 'https://my-site/js';

module.exports = {
  context: __dirname,
  entry: './app/frontend/entry.jsx',
  output: {
    path: path.resolve(__dirname, 'app', 'public', 'js'),
    publicPath: PUBLIC_PATH,
    filename: 'bundle.js',
  },
  plugins: [new RollbarSourceMapPlugin({
    accessToken: '---------------------------',
    version: '0.0.1',
    publicPath: PUBLIC_PATH,
  })],
  module: {
    loaders: [
      {
        test: [/\.jsx?$/, /\.js?$/],
        exclude: /node_modules/,
        loader: 'babel-loader',
        query: {
          presets: ['es2015', 'react'],
        },
      }, {
        test: /\.scss$/,
        loaders: ['style-loader', 'css-loader', 'sass-loader'],
      },
    ],
  },
  devtool: 'source-map',
  resolve: {
    extensions: ['.js', '.jsx', '*'],
  },
};
```

Am I doing something wrong, or misunderstanding something conceptually?

**Comment by jasonbarry** [comment]
@ailadson did you see this issue? https://github.com/thredup/rollbar-sourcemap-webpack-plugin/issues/44

Try setting `sourceMap: true` in your uglify config.

**Comment by saschwarz** [comment]
@ailadson I was confused by the Rollbar source map dashboard when I first used it. It shows the "Minified URL" not the source map url as you might expect. If you click on the download button (hover over the source map entry) the source map associated with the Minified URL is downloaded. HTH.
