### ISSUE TITLE
Can I add a web pack hash to the version?

### ISSUE THREAD

**Issue by ihorsavka** [thredup/rollbar-sourcemap-webpack-plugin#55]
When i add hash to the version ```version: "[hash]"``` in the rollbar iger version as a string => "[hash]" but as i understand webpack it should change the string as a real hash. Is there a vay to put there a webpack hash not using web pack way ?

**Comment by brandondoran** [comment]
@ihorsavka Sorry, I'm not understanding the question. If it's still relevant issue, can you please clarify?

**Comment by brandondoran** [comment]
Closing for lack of information.  Feel free to re-open and provide clarification.
