### ISSUE TITLE
Were there actually any breaking changes in v2?

### ISSUE THREAD

**Issue by MatthewHerbst** [thredup/rollbar-sourcemap-webpack-plugin#59]
From the [CHANGELOG](https://github.com/thredup/rollbar-sourcemap-webpack-plugin/blob/master/CHANGELOG.md) or the "[Full Changelog](https://github.com/thredup/rollbar-sourcemap-webpack-plugin/compare/v1.7.0...v2.0.0)" there do not appear to be any breaking changes in v2, though it was a major version bump. Can you please confirm this? I'm looking to upgrade from v1.

**Comment by brandondoran** [comment]
@MatthewHerbst yes that's correct. v2 should be backwards compatible. It probably shouldn't have been a major version bump.

**Comment by MatthewHerbst** [comment]
Thanks @brandondoran for the quick response and the confirmation.
