### ISSUE TITLE
Nextjs fn example

### ISSUE THREAD

**Issue by stubar** [thredup/rollbar-sourcemap-webpack-plugin#67]
Hi I understand that the public path as function was added to help NextJS users.  I wonder if anyone has an example of using this function, I am scratching my head trying to convert 
```static/chunks/0.js```
to 
```https://mydomain.com/_next/static/chunks/1257.4018bf3adeea4baca07e.js````

**Comment by drewlustro** [comment]
I also would like an example. The README specifically mentions Nextjs, but does not have a working example

**Comment by jamesmosier** [comment]
@brandondoran does Next.js work out of the box? I noticed it puts bundles into multiple folders (i.e. `static/runtime` and `static/chunks`)?

Therefore the `publicPath` could be `https://domain.com/_next/static/`?

**Comment by pjaws** [comment]
@jamesmosier but then you have the build ID after that. Also, I too, would like an actual example of this. It's really bizarre that the author specifically mentions this, but provides no example or API documentation on what the function is supposed to look like.

**Comment by jamesmosier** [comment]
I created an example (up for PR #83) that worked for me in a production application. Give it a try and let me know if there are any updates needed.
