### ISSUE TITLE
Documentation example is misleading for using hidden source maps

### ISSUE THREAD

**Issue by imperio59** [thredup/rollbar-sourcemap-webpack-plugin#69]
I was trying to use this plugin to upload my source maps during deployment, after which I deleted them before uploading my app to my server.

The issue is that with the example config on the README file, comments get inserted into the generated JS bundles with the URL of the source map. This makes the source maps public (which is generally a bad idea) and defeats the whole purpose of using this plugin to upload them to rollbar.

What's required in addition to the example config is to add the following so webpack doesn't emit comments with source map URLs in the bundled files, and so rollbar will use the files uploaded by the plugin instead of trying to re-download them when an error fires:

`    devtool: 'hidden-source-map',`

This is documented here: https://survivejs.com/webpack/building/source-maps/#devtool-hidden-source-map-

Can you please update your README to add this line in the sample config with a comment about its relevance? Thanks!

**Comment by brandondoran** [comment]
Good point. I will update the usage example and include more documentation on the importance of `hidden-source-map`.
